apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 902542926791.dkr.ecr.us-west-2.amazonaws.com/guestbook
  newTag: 2e3a484a4bedf6c95f89211627f9fbbd84fa7913
- name: frontend
  newName: guestbook
  newTag: new
- name: guestbook
  newName: guestbook
  newTag: new
