# build.yml
on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.html"
  push:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.html"
    branches: # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master # triggers on pushes that contain changes in master

name: Build and Push an Image to ECR

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_OUTPUT: json
  IMAGE_NAME: guestbook

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      # Add steps here like linting, testing, minification, etc.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=raw,value=${{ github.sha }}
            type=raw,value=${{ github.short_ref }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./php-redis
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # Set image tag in kustomization

      - name: Set image tag
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd deploy
          kustomize edit set image $ECR_REGISTRY/$IMAGE_NAME:${{ github.sha }}
          cat kustomization.yaml
      - name: Commit kustomization
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "$IMAGE_NAME:${{ github.sha }}"
      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
